version: "3"
services:
  lemmingpants-frontend:
    image: lemmingpants-frontend:latest
    container_name: lemmingpants-frontend
    volumes:
      - ../frontend:/srv/frontend/
      - ../static:/srv/static/
    working_dir: /srv/frontend
    entrypoint: make

  lemmingpants-backend:
    image: lemmingpants-backend:latest
    container_name: lemmingpants-backend
    restart: always
    environment:
      PGRST_DB_URI: postgres://lemmingpants:lemmingpants@localhost/lemmingpants
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_POOL: 10
      PGRST_SERVER_HOST: "*4"
      PGRST_SERVER_PORT: 8000
      PGRST_WS_ROOT: /srv/static/
      PGRST_WS_LISTEN: postgres-websockets-listener
      # PGWS_JWT_SECRET is initialized when you start the container.
      # It has been generated during installation.
    ports:
      - "5432:5432"
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ../static:/srv/static
    entrypoint: /usr/local/bin/run_backend.sh
